[FEAT] 카카오 로그인 API 구현
Team-OYA/backend pull request #6
Opened 2024-02-15 02:10 UTC by sangminee

카카오 로그인 API 구현했슴돠~

2024-02-15 03:24 UTC, kyukong requested changes
지금 진행하고 있는 파트까지 리뷰하고 approve 하겠습니다!!! ㅎㅎㅎ

2024-02-15 03:24 UTC, kyukong commented on src/main/java/com/oya/kr/user/controller/client/KakaoApiClient.java
> +		URI uri = URI.create("https://kapi.kakao.com/v2/user/me");
yml 파일이나 properties 파일로 분리하면 더 좋을 것 같아요!

2024-02-15 03:24 UTC, kyukong commented on src/main/java/com/oya/kr/user/controller/client/KakaoApiClient.java
> +		RestTemplate restTemplate = new RestTemplate();
RestTemplate 은 데이터를 가지는 객체가 아니기 때문에 별도의 객체로 생성 후 RestTemplate 을 static 필드로 가지고 있다면 자원 사용을 줄일 수 있을 것 같아용

2024-02-15 03:24 UTC, kyukong commented on src/main/java/com/oya/kr/user/controller/dto/request/AccessTokenRequest.java
> +}
필드에 final 이 있어야 관련 생성자가 만들어집니당!!

2024-02-15 03:24 UTC, kyukong commented on src/main/java/com/oya/kr/user/service/KaKaoLoginService.java
> +		return new JwtTokenResponse("Bearer ", accessToken, refreshToken);
`Bearer` 타입이 다른 코드에서도 사용되어, 관련 객체 또는 Enum 으로 분리하면 어떤가요??

2024-02-15 03:24 UTC, kyukong commented on src/test/java/com/oya/kr/user/service/KaKaoLoginServiceTest.java
> +		assertEquals("SampleNickname", user.getNickname());
assertAll 을 사용하여 묶으면 한번에 처리할 수 있습니다!! 다만 assertAll 안에 순서를 보장하지 않는다는 단점이 있지만.. 그래도 하나의 테스트에서 하나의 검증으로 묶는 편이 좋을 것 같아요 ㅎㅎ

2024-02-16 00:22 UTC, sangminee commented
/resources/application.properties  노션에 올려놨으니 secret 폴더 싹 지우고 해당 파일로 추가해 주세용~

2024-02-16 00:24 UTC, kyukong approved these changes
드디어 카카오 로그인 기능이 추가되었네요! ㅎㅎㅎ 수고 많으셨습니다!

2024-02-16 00:26 UTC, merged